export const projectsData=[
    {
        title:"Wasaly",
        description:`Wasaly is web application connecting customers with delivery services and products providers.
        Its aim to ease the process of buying from local stores giving the customers the ability to get their products from anywhere via delivery service and the local stores the ability to connect to delivery service to eliminate the hustle of providing delivery service and to sell their products and a way to reach more customers.`,
        languages:"ReactJS & NodeJS",
        featuresIDeveloped:[
            "User can Search for products",
            "User can report service",
            "User can Filter products by name and brand name",
            "User can Rate and review for service owners for order",
            "Landing page",
            "Login by Google",
            "Verification of email in registration",
            "Orders/order info page(view)",
            "CRUD Operations for products (product owner)",
            "product Cards",
            "Infinite scrolling and pagination",
            "Sending Notification to service owners connected to the product owner when a order is placed"
        ],
        team:true,
        img:"wasaly-01.png",
        img2:"wasaly-02.png",
        githublink:"https://github.com/mohamedadham/Wasaly",
        link:"https://drive.google.com/file/d/1WlfRt4s3z7r5-zKuoypGr8HAf1dWoLPB/view?fbclid=IwAR0rYT8bQmXt2drdmKps5jivOH6LylkZ64qqwtpoHKAvD5-akQap3Blacjs",
        id:1,
    },
    {
        title:"Yalanotlob - MEAN",
        description:`Yalanotlob is web application allows the users to make order and add friends or group of friends to their orders.`,
        languages:"Angular 9 & NodeJS & Mongoose",
        featuresIDeveloped:[
            "Session based Authentication System",
            "User can add friends",
            "User can create group",
            "User can place order",
            "User can add friend(s) or a group to his order",
            "User can add/remove his items to the order he created or invited to.",
            "User created the order can cancel/finish it, add/remove any items/order's members.",
            "Push notifications to user when he is invited to order or invited friend joins his order."
        ],
        team:false,
        img:"yalanotlob-mean01.png",
        img2:"yalanotlobmean-02.png",
        githublink:"https://github.com/mohamedadham/Yallanotlob--MEAN",
        link:"https://drive.google.com/file/d/1e5gW4o4ap1qyKcWwAnSEir0XvyJsWWRI/view",
        id:2,
    },
    {
        title:"GoodReads MockUp",
        description:"It is a Web Application is meant to be as a mock for Good Reads functionalities for developing and learning issues and not by any means violating copyrights. It has two views the admin and user views.",
        languages:"ReactJS & NodeJS",
        featuresIDeveloped:[
            "Login and JWT",
            "Book Information",
            "User's Books",
        ],
        team:true,
        img:"goodreads-01.png",
        githublink:"https://github.com/mohamedadham/goodreads-mock",
        id:3,
    },
    {
        title:"Library Management System",
        description:"It is a Web Application for automating the book leasing and management process of Libraries. It is implemented in Laravel and has two views the admin and user views.",
        languages:"Laravel",
        team:true,
        featuresIDeveloped:[
            "User can update his profile",
            "User can filter books by category",
            "User can lease book",
        ],
        img:"bookstore-02.png",
        img2:"book store-01.png",
        githublink:"https://github.com/mohamedadham/Library-Management-System",
        id:4,
    },
    {
        title:"CrowFunding",
        description:"It is a Web Application for automating the projects' funding activity. It has two views the admin and user views. ",
        languages:"Django",
        team:true,
        featuresIDeveloped:[
            "User can donate",
            "User can edit his profile",
            "User can search for project by title",
            "User can filter projects by category",
        ],
        img:"crowd-01.png.png",
        githublink:"https://github.com/mohamedadham/Crowd-Funding-System",
        id:5,
    },
    {
        title:"Yalanotlob",
        description:"Yalanotlob is web application allows the users to make order and add friends or group of friends to their orders.",
        languages:"Rails",
        team:true,
        featuresIDeveloped:[
            "List User's Orders",
            "Notification System",
            "Latest Orders",
        ],
        img:"yalanotlob-01.png",
        githublink:"https://github.com/mohamedadham/Yalanotlob",
        id:6,
    },
    {
        title:"Cafe",
        description:"It is a Web Application for automating the ordering and management process of Cafeterias. It is implemented in PHP and has two views the admin and user views.",
        languages:"PHP",
        featueresIDeveloped:"",
        team:true,
        img:"cafe-01.png",
        githublink:"https://github.com/mohamedadham/Cafe-php-project",
        id:7,
    },
    {
        title:"Resort Beach",
        description:"Web application to book a room from resort",
        languages:"ReactJS",
        team:false,
        img:"resort-01.png",
        link:"https://react-resort-app-tutorial.netlify.app/",
        githublink:"https://github.com/mohamedadham/react-beach-resort-tutorial",
        id:8,
    },
    {
        title:"Store and Cart",
        description:"Small project simulate listing products and user can add products to cart",
        languages:"ReactJS",
        team:false,
        img:"store-01.png",
        img2:"store-02.png",
        link:"https://mohamedadham.github.io/store/",
        githublink:"https://github.com/mohamedadham/store",
        id:9,
    },
    {
        title:"Pomodoro",
        description:"The Pomodoro Technique is a time management method.  The technique uses a timer to break down work into intervals, 25 minutes in length, separated by short breaks.",
        languages:"ReactJS",
        team:false,
        img:"pomodoro-01.png",
        link:"https://pomodoro-clock-using-react.herokuapp.com/",
        githublink:"https://github.com/mohamedadham/pomodoroClockReact",
        id:10,
    },
    {
        title:"TodoList",
        description:"User can add/remove item from todolist and mark item as important",
        languages:"ReactJS",
        team:false,
        img:"todo-01.png",
        link:"https://todolistappreact.herokuapp.com/",
        githublink:"https://github.com/mohamedadham/TodoApp",
        id:11,
    }
]


                  